jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Build with Gradle
      run: 'bash ./gradlew build --stacktrace

        '
    - continue-on-error: true
      name: Store APK file
      uses: actions/upload-artifact@v3
      with:
        name: apk-files
        path: 'app/build/outputs/apk/debug/app-debug.apk

          '
name: Build
on:
  repository_dispatch:
    types: trigger-ga___pull-request.yml
